version: "3.3"
services:
  influxdb:
    image: influxdb
    volumes:
      - "influxdb_data:/var/lib/influxdb"
    ports:
      - "8086:8086" 
    read_only: true

  telegraf:
    image: telegraf
    configs:
      - source: telegraf.conf
        target: /etc/telegraf/telegraf.conf
        mode: 0444
    read_only: true

  mqtt:
    image: eclipse-mosquitto
    ports: 
      - "1883:1883"
    read_only: false

  grafana:
    image: grafana/grafana
    volumes:
      - "grafana_data:/var/lib/grafana"
    configs:
      - source: grafana.ini
        target: /etc/grafana/grafana.ini
        mode: 0444
    environment:
      - GF_DATABASE_PASSWORD__FILE=/run/secrets/grafana_db_password
      - GF_DATABASE_HOST__FILE=/run/secrets/db_host
      - GF_SERVER_DOMAIN__FILE=/run/secrets/grafana_domain
      - GF_SERVER_ROOT_URL__FILE=/run/secrets/grafana_root_url
    secrets:
      - grafana_db_password
      - grafana_domain
      - grafana_root_url
      - db_host
        
    deploy:
      placement:
        constraints:
          - node.role == manager
    user: "1000"
    networks:
      - default
      - web_proxy
    labels:
      external-hostname: 'grafana'
      external-port: 3000

    # read_only: true %TODO

volumes:    
  influxdb_data:
    driver_opts:
      type: "nfs"
      o: "addr=acropolis"
      device: ":/mnt/block1/docker-volumes/influxdb"

  grafana_data:
    

networks:
  web_proxy:
    external:
      name: web_proxy

configs:
  telegraf.conf:
    file: ./configs/telegraf.conf
  grafana.ini:
    file: ./configs/grafana.ini

secrets:
  grafana_db_password:
    external: true
  grafana_domain:
    external: true
  grafana_root_url:
    external: true
  db_host:
    external: true
